apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  type: NodePort
  ports:
  - port: 9080
    name: demo-service
    targetPort: 9080
  selector:
    app: demo-service
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
      - name: demo-service
        image: maeddes/demo-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
